project:
  type: website
  output-dir: docs  

website:
  title: "Gallery Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - primer.qmd
      - regression.qmd   
      - np_npRmpi.qmd
      - crs.qmd
      - interactive.qmd
      - function_index.qmd
      - R_RStudio.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



