<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="np, npRmpi, methods, theory, crosswalk, documentation">
<meta name="description" content="A practical map from np and npRmpi functions to statistical targets, examples, implementation notes, and theory references.">

<title>Method Crosswalk – Gallery of Code</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./books_papers.html" rel="next">
<link href="./function_index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6359ece5ccc7868d972a7c02362e1435.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Gallery of Code</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JeffreyRacine/gallery"> <i class="bi bi-github" role="img" aria-label="Gallery source on GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./faq.html">Support</a></li><li class="breadcrumb-item"><a href="./method_book_code_crosswalk.html">Method Crosswalk</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Start Here</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./primer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Choose a Package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Install and Get Started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quickstarts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quickstarts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Methods</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./np_npRmpi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kernel Methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kernel_primer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kernel Primer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./density_distribution_quantiles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Density, Distribution, Quantiles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification_modes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification and Modes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./semiparametric_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semiparametric Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./significance_and_specification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Significance and Specification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./entropy_tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Entropy and Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./npksum_custom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Build With npksum</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mpi_large_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MPI and Large Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Splines</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spline_primer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spline Primer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spline_search_and_tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spline Search and Tuning</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Examples</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_catalog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Code Catalog</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Worked Examples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multivariate_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multivariate Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./plotting_and_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plotting and Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interactive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactive Demos</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Support</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./faq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FAQ and Troubleshooting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Preparation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./runtime_and_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Runtime and Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./function_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./method_book_code_crosswalk.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Method Crosswalk</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./books_papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Books, Papers, and Citation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./legacy_materials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Legacy Materials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-to-use-this-page" id="toc-how-to-use-this-page" class="nav-link active" data-scroll-target="#how-to-use-this-page">How To Use This Page</a></li>
  <li><a href="#core-methods" id="toc-core-methods" class="nav-link" data-scroll-target="#core-methods">Core Methods</a>
  <ul class="collapse">
  <li><a href="#core-method-source-pointers" id="toc-core-method-source-pointers" class="nav-link" data-scroll-target="#core-method-source-pointers">Core Method Source Pointers</a></li>
  </ul></li>
  <li><a href="#tests-and-diagnostics" id="toc-tests-and-diagnostics" class="nav-link" data-scroll-target="#tests-and-diagnostics">Tests And Diagnostics</a>
  <ul class="collapse">
  <li><a href="#test-source-pointers" id="toc-test-source-pointers" class="nav-link" data-scroll-target="#test-source-pointers">Test Source Pointers</a></li>
  </ul></li>
  <li><a href="#advanced-and-workflow-apis" id="toc-advanced-and-workflow-apis" class="nav-link" data-scroll-target="#advanced-and-workflow-apis">Advanced And Workflow APIs</a></li>
  <li><a href="#book-source-key" id="toc-book-source-key" class="nav-link" data-scroll-target="#book-source-key">Book Source Key</a>
  <ul class="collapse">
  <li><a href="#princeton" id="toc-princeton" class="nav-link" data-scroll-target="#princeton">Princeton</a></li>
  <li><a href="#cambridge" id="toc-cambridge" class="nav-link" data-scroll-target="#cambridge">Cambridge</a></li>
  </ul></li>
  <li><a href="#reading-and-citation-links" id="toc-reading-and-citation-links" class="nav-link" data-scroll-target="#reading-and-citation-links">Reading And Citation Links</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/JeffreyRacine/gallery/blob/main/method_book_code_crosswalk.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./faq.html">Support</a></li><li class="breadcrumb-item"><a href="./method_book_code_crosswalk.html">Method Crosswalk</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Method Crosswalk</h1>
</div>

<div>
  <div class="description">
    A practical map from np and npRmpi functions to statistical targets, examples, implementation notes, and theory references.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>np, npRmpi, methods, theory, crosswalk, documentation</p>
  </div>
</div>

</header>


<style>
#quarto-document-content table {
  width: 100%;
}
#quarto-document-content th,
#quarto-document-content td {
  vertical-align: top;
  overflow-wrap: break-word;
  word-break: normal;
}
#quarto-document-content th code,
#quarto-document-content td code,
#quarto-document-content .math.inline {
  white-space: nowrap;
  overflow-wrap: normal;
  word-break: normal;
}
.crosswalk-core-methods th:nth-child(4),
.crosswalk-core-methods td:nth-child(4),
.crosswalk-test-methods th:nth-child(4),
.crosswalk-test-methods td:nth-child(4) {
  min-width: 12rem;
}
#refs,
#refs a,
.csl-entry,
.csl-entry a {
  overflow-wrap: anywhere;
}
@media (max-width: 700px) {
  #quarto-document-content table {
    display: block;
    max-width: 100%;
    overflow-x: auto;
  }
}
</style>
<p>This page maps the main <code>np</code> and <code>npRmpi</code> function families to the statistical object being estimated, the Gallery examples that are most useful to start with, and the book chapters where the method is developed or discussed.</p>
<p>It is not a replacement for the package help pages. Use <code>?npreg</code>, <code>?npcdens</code>, <code>?npconmode</code>, and related help pages for argument-level details. This page is meant to answer a different question: “What method am I using, where is it explained, and how does it connect to the package implementation?”</p>
<p>The Princeton book <span class="citation" data-cites="book-li_2007">(<a href="#ref-book-li_2007" role="doc-biblioref">Li and Racine 2007</a>)</span> is the foundational theory reference for many of the core mixed-data kernel estimators. The Cambridge book <span class="citation" data-cites="book-racine_cambridge_2019">(<a href="#ref-book-racine_cambridge_2019" role="doc-biblioref">Racine 2019a</a>)</span> is later and more package/workflow oriented, and it covers additional examples, entropy-based material, semiparametric workflows, and computational considerations. This crosswalk therefore points to the most useful source for each method rather than treating one book as the only route.</p>
<p>Implementation details added after the printed treatments, such as recent local-polynomial degree search, conditional-quantile gradients, or MPI-aware plot/bootstrap machinery, are labeled as package implementation extensions.</p>
<section id="how-to-use-this-page" class="level2">
<h2 class="anchored" data-anchor-id="how-to-use-this-page">How To Use This Page</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>If you want…</th>
<th>Use this route</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Runnable examples</td>
<td>Start with the Gallery page linked in the method row.</td>
</tr>
<tr class="even">
<td>Argument details</td>
<td>Open the package help page in R.</td>
</tr>
<tr class="odd">
<td>Theory and derivations</td>
<td>Use the chapter and section pointers listed here.</td>
</tr>
<tr class="even">
<td>MPI behavior</td>
<td>Read the method row, then see <a href="./mpi_large_data.html">MPI and Large Data</a>.</td>
</tr>
<tr class="odd">
<td>Function lookup</td>
<td>Use <a href="./function_index.html">Reference and Function Lookup</a>.</td>
</tr>
</tbody>
</table>
</section>
<section id="core-methods" class="level2">
<h2 class="anchored" data-anchor-id="core-methods">Core Methods</h2>
<div class="crosswalk-core-methods">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Task</th>
<th>Main functions</th>
<th>Statistical target</th>
<th>Best first Gallery page</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td><code>npreg</code>, <code>npregbw</code></td>
<td>Conditional mean or regression function <span class="math inline">\(E[Y \mid X=x]\)</span></td>
<td><a href="./kernel_primer.html">Kernel Primer</a>, <a href="./regression.html">Worked Examples</a></td>
</tr>
<tr class="even">
<td>Unconditional density</td>
<td><code>npudens</code>, <code>npudensbw</code></td>
<td>Density <span class="math inline">\(f(x)\)</span></td>
<td><a href="./density_distribution_quantiles.html">Density, Distribution, Quantiles</a></td>
</tr>
<tr class="odd">
<td>Unconditional distribution</td>
<td><code>npudist</code>, <code>npudistbw</code></td>
<td>Distribution <span class="math inline">\(F(x)\)</span></td>
<td><a href="./density_distribution_quantiles.html">Density, Distribution, Quantiles</a></td>
</tr>
<tr class="even">
<td>Conditional density</td>
<td><code>npcdens</code>, <code>npcdensbw</code></td>
<td>Conditional density <span class="math inline">\(f(y \mid x)\)</span></td>
<td><a href="./density_distribution_quantiles.html">Density, Distribution, Quantiles</a></td>
</tr>
<tr class="odd">
<td>Conditional distribution</td>
<td><code>npcdist</code>, <code>npcdistbw</code></td>
<td>Conditional distribution <span class="math inline">\(F(y \mid x)\)</span></td>
<td><a href="./density_distribution_quantiles.html">Density, Distribution, Quantiles</a></td>
</tr>
<tr class="even">
<td>Conditional quantile</td>
<td><code>npqreg</code></td>
<td>Conditional quantile <span class="math inline">\(q_\tau(x)=\inf\{y:F(y \mid x)\ge \tau\}\)</span></td>
<td><a href="./density_distribution_quantiles.html">Density, Distribution, Quantiles</a></td>
</tr>
<tr class="odd">
<td>Conditional mode / classification</td>
<td><code>npconmode</code></td>
<td>Modal outcome <span class="math inline">\(\arg\max_y \Pr(Y=y \mid X=x)\)</span></td>
<td><a href="./classification_modes.html">Classification and Modes</a></td>
</tr>
<tr class="even">
<td>Partially linear regression</td>
<td><code>npplreg</code>, <code>npplregbw</code></td>
<td>Partially linear model <span class="math inline">\(Y=X'\beta+\theta(Z)+\epsilon\)</span></td>
<td><a href="./semiparametric_models.html">Semiparametric Models</a></td>
</tr>
<tr class="odd">
<td>Single-index model</td>
<td><code>npindex</code>, <code>npindexbw</code></td>
<td>Index regression <span class="math inline">\(E[Y \mid X]=g(X'\beta)\)</span></td>
<td><a href="./semiparametric_models.html">Semiparametric Models</a></td>
</tr>
<tr class="even">
<td>Smooth-coefficient model</td>
<td><code>npscoef</code>, <code>npscoefbw</code></td>
<td>Varying coefficients <span class="math inline">\(Y=X'\beta(Z)+\epsilon\)</span></td>
<td><a href="./semiparametric_models.html">Semiparametric Models</a></td>
</tr>
</tbody>
</table>
</div>
<section id="core-method-source-pointers" class="level3">
<h3 class="anchored" data-anchor-id="core-method-source-pointers">Core Method Source Pointers</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Task</th>
<th>Theory and implementation orientation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>Princeton, <em>Regression</em>, Chapter 2, especially Sections 2.1, 2.2, 2.4, and 2.5; Princeton, <em>Kernel Estimation with Mixed Data</em>, Chapter 4, especially Sections 4.2 and 4.4; Cambridge, <em>Conditional Mean Function Estimation</em>, Chapter 6. Local-polynomial and automatic degree-search options can materially change the fitted estimator. The current <code>ll</code> route is implemented as local polynomial degree 1 where applicable.</td>
</tr>
<tr class="even">
<td>Unconditional density</td>
<td>Princeton, <em>Density Estimation</em>, Chapter 1, especially Sections 1.1, 1.3, 1.6, 1.8, and 1.9; Princeton, <em>Kernel Estimation with Mixed Data</em>, Chapter 4; Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2; Cambridge, <em>Mixed-Data Probability Density and Cumulative Distribution Functions</em>, Chapter 3.</td>
</tr>
<tr class="odd">
<td>Unconditional distribution</td>
<td>Princeton, <em>Density Estimation</em>, Chapter 1, especially Sections 1.4 and 1.5; Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2, especially smooth kernel CDF material; Cambridge, <em>Mixed-Data Probability Density and Cumulative Distribution Functions</em>, Chapter 3.</td>
</tr>
<tr class="even">
<td>Conditional density</td>
<td>Princeton, <em>Conditional Density Estimation</em>, Chapter 5, especially Sections 5.1-5.4; Princeton, <em>Kernel Estimation with Mixed Data</em>, Chapter 4; Cambridge, <em>Conditional Probability Density and Cumulative Distribution Functions</em>, Chapter 4.</td>
</tr>
<tr class="odd">
<td>Conditional distribution</td>
<td>Princeton, <em>Conditional CDF and Quantile Estimation</em>, Chapter 6, especially Sections 6.1, 6.2, and 6.5; Princeton, <em>Conditional Density Estimation</em>, Chapter 5; Cambridge, <em>Conditional Probability Density and Cumulative Distribution Functions</em>, Chapter 4.</td>
</tr>
<tr class="even">
<td>Conditional quantile</td>
<td>Princeton, <em>Conditional CDF and Quantile Estimation</em>, Chapter 6, especially Sections 6.3-6.5; Cambridge, <em>Conditional Probability Density and Cumulative Distribution Functions</em>, Chapter 4, especially conditional CDF and quantile material; Nelsen (2006) for quasi-inverse language. Gradients and standard errors are recent implementation extensions.</td>
</tr>
<tr class="odd">
<td>Conditional mode / classification</td>
<td>Cambridge, <em>Conditional Probability Density and Cumulative Distribution Functions</em>, Chapter 4, especially <em>Binary Choice and Multinomial Choice Models</em>; Princeton, <em>Conditional Density Estimation</em>, Chapter 5; Princeton, <em>Kernel Estimation with Mixed Data</em>, Chapter 4. Non-local-constant routes use proper fitted probabilities before modal selection.</td>
</tr>
<tr class="even">
<td>Partially linear regression</td>
<td>Princeton, <em>Semiparametric Partially Linear Models</em>, Chapter 7, especially Sections 7.1, 7.2, and 7.4; Cambridge, <em>Semiparametric Conditional Mean Function Estimation</em>, Chapter 8, especially <em>Robinson’s Partially Linear Model</em>. Current local-polynomial/NOMAD behavior treats the nuisance regressions as child-specific local-polynomial fits, followed by the final partially linear solve.</td>
</tr>
<tr class="odd">
<td>Single-index model</td>
<td>Princeton, <em>Semiparametric Single Index Models</em>, Chapter 8, especially Sections 8.1, 8.2.1, 8.4, 8.5, and 8.10; Cambridge, <em>Semiparametric Conditional Mean Function Estimation</em>, Chapter 8, especially single-index material.</td>
</tr>
<tr class="even">
<td>Smooth-coefficient model</td>
<td>Princeton, <em>Additive and Smooth (Varying) Coefficient Semiparametric Models</em>, Chapter 9, especially Sections 9.3-9.3.4; Cambridge, <em>Semiparametric Conditional Mean Function Estimation</em>, Chapter 8, especially <em>Varying Coefficient Models</em>.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="tests-and-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="tests-and-diagnostics">Tests And Diagnostics</h2>
<div class="crosswalk-test-methods">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Task</th>
<th>Main functions</th>
<th>What the test asks</th>
<th>Best first Gallery page</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean model specification</td>
<td><code>npcmstest</code></td>
<td>Does a parametric conditional-mean model appear misspecified against a nonparametric alternative?</td>
<td><a href="./significance_and_specification.html">Significance and Specification</a></td>
</tr>
<tr class="even">
<td>Quantile model specification</td>
<td><code>npqcmstest</code></td>
<td>Does a parametric conditional-quantile model appear misspecified?</td>
<td><a href="./significance_and_specification.html">Significance and Specification</a></td>
</tr>
<tr class="odd">
<td>Significance testing</td>
<td><code>npsigtest</code></td>
<td>Which regressors are statistically relevant in a nonparametric regression?</td>
<td><a href="./significance_and_specification.html">Significance and Specification</a></td>
</tr>
<tr class="even">
<td>Density equality</td>
<td><code>npdeneqtest</code></td>
<td>Are distributions or densities equal across groups?</td>
<td><a href="./entropy_tests.html">Entropy and Testing</a></td>
</tr>
<tr class="odd">
<td>Univariate density features</td>
<td><code>npunitest</code></td>
<td>Does a univariate density have the specified feature?</td>
<td><a href="./entropy_tests.html">Entropy and Testing</a></td>
</tr>
<tr class="even">
<td>Symmetry</td>
<td><code>npsymtest</code></td>
<td>Is a distribution symmetric?</td>
<td><a href="./entropy_tests.html">Entropy and Testing</a></td>
</tr>
<tr class="odd">
<td>Dependence</td>
<td><code>npdeptest</code>, <code>npsdeptest</code></td>
<td>Are variables dependent or serially dependent?</td>
<td><a href="./entropy_tests.html">Entropy and Testing</a></td>
</tr>
</tbody>
</table>
</div>
<section id="test-source-pointers" class="level3">
<h3 class="anchored" data-anchor-id="test-source-pointers">Test Source Pointers</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Task</th>
<th>Theory and implementation orientation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean model specification</td>
<td>Princeton, <em>Model Specification Tests</em>, Chapter 12, especially Section 12.1 and Section 12.1.2; Cambridge, <em>Conditional Mean Function Estimation</em>, Chapter 6, for package-facing model assessment context.</td>
</tr>
<tr class="even">
<td>Quantile model specification</td>
<td>Princeton, <em>Model Specification Tests</em>, Chapter 12; Princeton, <em>Conditional CDF and Quantile Estimation</em>, Chapter 6; Cambridge, <em>Conditional Probability Density and Cumulative Distribution Functions</em>, Chapter 4.</td>
</tr>
<tr class="odd">
<td>Significance testing</td>
<td>Princeton, <em>Model Specification Tests</em>, Chapter 12, especially Sections 12.3 and 12.3.5; Princeton, <em>Nonsmoothing Tests</em>, Chapter 13, especially Section 13.3 where applicable; Cambridge, <em>Conditional Mean Function Estimation</em>, Chapter 6.</td>
</tr>
<tr class="even">
<td>Density equality</td>
<td>Princeton, <em>Model Specification Tests</em>, Chapter 12, especially Section 12.2; Princeton, <em>Nonsmoothing Tests</em>, Chapter 13, especially Section 13.2; Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2, and <em>Mixed-Data Probability Density and Cumulative Distribution Functions</em>, Chapter 3.</td>
</tr>
<tr class="odd">
<td>Univariate density features</td>
<td>Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2, especially entropy and density-test material; Princeton testing chapters where applicable.</td>
</tr>
<tr class="even">
<td>Symmetry</td>
<td>Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2; Princeton, <em>Nonsmoothing Tests</em>, Chapter 13, and <em>Model Specification Tests</em>, Chapter 12, where density-feature tests are treated.</td>
</tr>
<tr class="odd">
<td>Dependence</td>
<td>Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2; Princeton, <em>Nonsmoothing Tests</em>, Chapter 13, especially Sections 13.4 and 13.5; Princeton, <em>Model Specification Tests</em>, Chapter 12, especially Sections 12.4.1 and 12.4.3.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="advanced-and-workflow-apis" class="level2">
<h2 class="anchored" data-anchor-id="advanced-and-workflow-apis">Advanced And Workflow APIs</h2>
<p>These functions are useful, but they are not the main starting point for most users.</p>
<ul>
<li><code>npksum</code>: lower-level mixed-kernel sums for custom workflows. Start with <a href="./npksum_custom.html">Build With npksum</a>. The relevant source is the estimator family being reconstructed; Cambridge, <em>Practicum</em>, Chapter 14, and <em>Computational Considerations</em>, Chapter 12, provide package-facing examples and computational context.</li>
<li><code>npreghat</code>, <code>npcdenshat</code>, <code>npcdisthat</code>, <code>npudenshat</code>, <code>npudisthat</code>, <code>npsemihat</code>: fast post-estimation and helper workflows. Start with <a href="./function_index.html">Reference and Function Lookup</a>. These are advanced APIs; their source usually follows the estimator family rather than a separate book derivation.</li>
<li><code>plot</code>, <code>se</code>, <code>gradients</code>, <code>compute.bootstrap.errors</code>: plot surfaces, intervals, standard errors, and derivative accessors. Start with <a href="./plotting_and_intervals.html">Plotting and Intervals</a>. Current plot/bootstrap and some gradient behavior are implementation extensions.</li>
<li><code>np.options</code>, <code>np.kernels</code>, <code>npseed</code>: reproducibility, global options, and kernel choices. Start with <a href="./kernel_primer.html">Kernel Primer</a>. Princeton, <em>Density Estimation</em>, Chapter 1, is the natural kernel/CDF background; package documentation is the source for exact option behavior.</li>
<li><code>npuniden.boundary</code>, <code>npuniden.reflect</code>, <code>npuniden.sc</code>, <code>uocquantile</code>: support and boundary workflows. Start with <a href="./function_index.html">Reference and Function Lookup</a>. Cambridge, <em>Continuous Density and Cumulative Distribution Functions</em>, Chapter 2, provides bounded-domain and boundary-correction context.</li>
<li><code>npcopula</code>: mixed-data copula and copula-density workflows. Start with <a href="./density_distribution_quantiles.html">Density, Distribution, Quantiles</a>. Cambridge, <em>Mixed-Data Probability Density and Cumulative Distribution Functions</em>, Chapter 3, especially <em>Smooth Kernel Copula Function Estimation with Mixed-Data</em>, and Princeton, <em>Topics in Applied Nonparametric Estimation</em>, Chapter 20, Section 20.4, are the main source pointers.</li>
<li><code>npregiv</code>, <code>npregivderiv</code>: instrumental-variable regression routes. Start with <a href="./function_index.html">Reference and Function Lookup</a>. Princeton, <em>Instrumental Variables and Efficient Estimation of Semiparametric Models</em>, Chapter 16, Princeton, <em>Endogeneity in Nonparametric Regression Models</em>, Chapter 17, and Cambridge, <em>Conditional Mean Function Estimation with Endogenous Predictors</em>, Chapter 7, are the main source pointers.</li>
<li><code>npRmpi.init</code>, <code>npRmpi.quit</code>, <code>npRmpi.session.info</code>: MPI setup, cleanup, and runtime diagnostics. Start with <a href="./mpi_large_data.html">MPI and Large Data</a>. Cambridge, <em>Computational Considerations</em>, Chapter 12, especially parallelism, provides general context; package runtime documentation is the source for exact behavior.</li>
</ul>
</section>
<section id="book-source-key" class="level2">
<h2 class="anchored" data-anchor-id="book-source-key">Book Source Key</h2>
<p>This section records the chapter-level map used above. It is intentionally chapter-first: if you own or can access the books, these are the places to start.</p>
<section id="princeton" class="level3">
<h3 class="anchored" data-anchor-id="princeton">Princeton</h3>
<ul>
<li>Chapter 1, <em>Density Estimation</em>: Sections 1.1, <em>Univariate Density Estimation</em>; 1.3, <em>Univariate Bandwidth Selection: Cross-Validation Methods</em>; 1.4, <em>Univariate CDF Estimation</em>; 1.5, <em>Univariate CDF Bandwidth Selection</em>; 1.6, <em>Multivariate Density Estimation</em>; 1.8, <em>Multivariate Bandwidth Selection</em>; 1.9, <em>Asymptotic Normality of Density Estimators</em>.</li>
<li>Chapter 2, <em>Regression</em>: Sections 2.1, <em>Local Constant Kernel Estimation</em>; 2.2, <em>Local Constant Bandwidth Selection</em>; 2.4, <em>Local Linear Kernel Estimation</em>; 2.5, <em>Local Polynomial Regression</em>.</li>
<li>Chapter 4, <em>Kernel Estimation with Mixed Data</em>: Sections 4.1, <em>Smooth Estimation of Joint Distributions with Discrete Data</em>; 4.2, <em>Smooth Regression with Discrete Data</em>; 4.4, <em>Regression with Mixed Data: Relevant Regressors</em>.</li>
<li>Chapter 5, <em>Conditional Density Estimation</em>: Sections 5.1, <em>Conditional Density Estimation: Relevant Variables</em>; 5.2, <em>Conditional Density Bandwidth Selection</em>; 5.3, <em>Conditional Density Estimation: Irrelevant Variables</em>; 5.4, <em>The Multivariate Dependent Variables Case</em>.</li>
<li>Chapter 6, <em>Conditional CDF and Quantile Estimation</em>: Sections 6.1-6.2, conditional CDF estimation; 6.3, <em>Nonparametric Estimation of Conditional Quantile Functions</em>; 6.5, mixed-data conditional CDF and quantile estimation.</li>
<li>Chapter 7, <em>Semiparametric Partially Linear Models</em>: Sections 7.1, <em>Partially Linear Models</em>; 7.2, <em>Robinson’s Estimator</em>; 7.4, <em>Semiparametric Efficiency Bounds</em>.</li>
<li>Chapter 8, <em>Semiparametric Single Index Models</em>: Sections 8.1, identification; 8.2.1, <em>Ichimura’s Method</em>; 8.4, bandwidth selection; 8.5, <em>Klein and Spady’s Estimator</em>; 8.10, multinomial discrete choice.</li>
<li>Chapter 9, <em>Additive and Smooth (Varying) Coefficient Semiparametric Models</em>: Sections 9.3-9.3.4, varying/smooth coefficient models and related tests.</li>
<li>Chapter 12, <em>Model Specification Tests</em>: Sections 12.1, parametric regression functional form; 12.2, equality of PDFs; 12.3, regression-function tests; 12.4, PDF-related tests.</li>
<li>Chapter 13, <em>Nonsmoothing Tests</em>: Sections 13.1, functional-form tests; 13.2, equality of densities; 13.3, significance testing; 13.4-13.5, conditional CDF and serial-dependence tests.</li>
<li>Chapter 16, <em>Instrumental Variables and Efficient Estimation of Semiparametric Models</em>: Sections 16.1-16.3, semiparametric IV models and conditional moment restrictions.</li>
<li>Chapter 17, <em>Endogeneity in Nonparametric Regression Models</em>: Sections 17.1-17.5, nonparametric IV/endogeneity models and estimators.</li>
<li>Chapter 20, <em>Topics in Applied Nonparametric Estimation</em>: Section 20.4, copula-based semiparametric estimation.</li>
</ul>
</section>
<section id="cambridge" class="level3">
<h3 class="anchored" data-anchor-id="cambridge">Cambridge</h3>
<ul>
<li>Chapter 2, <em>Continuous Density and Cumulative Distribution Functions</em>: smooth kernel density, CDF, and quantile estimation; multivariate extensions; entropy and information measures; bounded-domain examples.</li>
<li>Chapter 3, <em>Mixed-Data Probability Density and Cumulative Distribution Functions</em>: mixed-data density/CDF estimation; multivariate extension; smooth kernel copula estimation with mixed data.</li>
<li>Chapter 4, <em>Conditional Probability Density and Cumulative Distribution Functions</em>: smooth conditional density; smooth conditional CDF; conditional quantile estimation; binary choice and multinomial choice models.</li>
<li>Chapter 6, <em>Conditional Mean Function Estimation</em>: local constant and local polynomial regression; multivariate local-polynomial extension; mixed-data marginal effects; predictor relevance; shape-constrained regression.</li>
<li>Chapter 7, <em>Conditional Mean Function Estimation with Endogenous Predictors</em>: ill-posed inverse problems and identification; parametric and nonparametric instrumental regression.</li>
<li>Chapter 8, <em>Semiparametric Conditional Mean Function Estimation</em>: Robinson’s partially linear model; varying coefficient models; semiparametric single-index models.</li>
<li>Chapter 12, <em>Computational Considerations</em>: binning, transforms, parallelism, tree/multipole methods, and computationally efficient kernel estimation in R.</li>
<li>Chapter 14, <em>Practicum</em>: applied <code>np</code> examples, <code>npksum()</code>, nonparametric density/regression, consistent inference, semiparametric models, and nonparametric discrete choice.</li>
</ul>
</section>
</section>
<section id="reading-and-citation-links" class="level2">
<h2 class="anchored" data-anchor-id="reading-and-citation-links">Reading And Citation Links</h2>
<p>For formal citation commands, package references, and broader reading, see <a href="./books_papers.html">Books, Papers, and Citation</a>.</p>
<p>Public companion links:</p>
<ul>
<li><a href="https://jeffreyracine.github.io/research/books.html">Research site book hub</a></li>
<li><a href="https://jeffreyracine.github.io/research/resources.html">Research site downloads/resources</a></li>
<li><a href="https://press.princeton.edu/books/hardcover/9780691121611/nonparametric-econometrics">Princeton book page</a></li>
<li><a href="https://jeffreyracine.github.io/research/www/pup_toc.pdf">Princeton table of contents</a></li>
<li><a href="https://jeffreyracine.github.io/research/www/pup_errata.pdf">Princeton errata</a></li>
<li><a href="https://press.princeton.edu/chapters/s8355.pdf">Princeton Chapter 1 sample</a></li>
<li><a href="https://www.cambridge.org/br/academic/subjects/economics/econometrics-statistics-and-mathematical-economics/introduction-advanced-theory-and-practice-nonparametric-econometrics-replicable-approach-using-r?format=HB">Cambridge book page</a></li>
<li><a href="https://global.oup.com/academic/product/reproducible-econometrics-using-r-9780190900663">Oxford book page</a></li>
<li><a href="https://jeffreyracine.github.io/research/www/ECO0301.pdf">Nonparametric Econometrics: A Primer</a></li>
</ul>
<p>The Research site surfaces public PDFs, errata, and code archives. Local manuscript sources, teaching files, solution material, and administrative files are not public resources unless they are explicitly published on the Research site or by a publisher.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-hayfield_2008" class="csl-entry" role="listitem">
Hayfield, T., and J. S. Racine. 2008. <span>“Nonparametric Econometrics: The <span class="nocase">np</span> Package.”</span> <em>Journal of Statistical Software</em> 27 (5): 1–32. <a href="https://doi.org/10.18637/jss.v027.i05">https://doi.org/10.18637/jss.v027.i05</a>.
</div>
<div id="ref-ho_2011" class="csl-entry" role="listitem">
Ho, A. T., K. P. Huynh, and D. T. Jacho-Chavez. 2011. <span>“<span class="nocase">npRmpi</span>: A Package for Parallel Distributed Kernel Estimation in <span>R</span>.”</span> <em>Journal of Applied Econometrics</em> 26: 344–49.
</div>
<div id="ref-book-li_2007" class="csl-entry" role="listitem">
Li, Q., and J. S. Racine. 2007. <em>Nonparametric Econometrics: Theory and Practice</em>. Princeton University Press. <a href="https://press.princeton.edu/books/hardcover/9780691121611/nonparametric-econometrics">https://press.princeton.edu/books/hardcover/9780691121611/nonparametric-econometrics</a>.
</div>
<div id="ref-nie_2012" class="csl-entry" role="listitem">
Nie, Z., and J. S. Racine. 2012. <span>“The Crs Package: Nonparametric Regression Splines for Continuous and Categorical Predictors.”</span> <em>The <span>R</span> Journal</em> 4 (2): 48–56. <a href="https://doi.org/10.32614/rj-2012-012">https://doi.org/10.32614/rj-2012-012</a>.
</div>
<div id="ref-book-racine_cambridge_2019" class="csl-entry" role="listitem">
Racine, J. S. 2019a. <em>An Introduction to the Advanced Theory and Practice of Nonparametric Econometrics: A Replicable Approach Using <span>R</span></em>. Cambridge University Press. <a href="https://doi.org/10.1017/9781108649841">https://doi.org/10.1017/9781108649841</a>.
</div>
<div id="ref-book-racine_2019b" class="csl-entry" role="listitem">
Racine, J. S. 2019b. <em>Reproducible Econometrics Using <span>R</span></em>. Oxford University Press. <a href="https://doi.org/10.1093/oso/9780190900663.001.0001">https://doi.org/10.1093/oso/9780190900663.001.0001</a>.
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jeffreyracine\.github\.io\/gallery\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./function_index.html" class="pagination-link" aria-label="Reference">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Reference</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./books_papers.html" class="pagination-link" aria-label="Books, Papers, and Citation">
        <span class="nav-page-text">Books, Papers, and Citation</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Working examples and notes for <code>np</code>, <code>npRmpi</code>, and <code>crs</code>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/JeffreyRacine/gallery/blob/main/method_book_code_crosswalk.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://jeffreyracine.github.io/research">
<p>Research site</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://cran.r-project.org/">
<p>CRAN</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>